theme: minima
title: Luke Jackson - Resume
author: Luke Jackson
email: luke.e.jackson@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
 Resume for Web Development
# social links
github_username:  Luke-E-Jackson # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
